### ISSUE TITLE
panic on "SELECT *"

### ISSUE THREAD

**Issue by gallypette** [cert-lv/graphoscope#3]
Hi there,
Trying various things with the search bar I found out that entering `SELECT *` makes the program to panic.

**Comment by aleksejsv** [comment]
Hello,

Can you please provide more info on how to reproduce this bug? Panic error's content also will be useful. When I try such query on my side with the latest version I get a normal GUI error notification `Unexpected SQL expression type received ...` and the service itself continues to work.

**Comment by gallypette** [comment]
sure, here is the panic:

```
2022-02-22T14:14:49+01:00 INF New request modified="select * from demo where (select * from dual) limit 0, 1000" sql="FROM demo WHERE (select *) AND datetime BETWEEN '2022-02-20T14:57:07.000Z' AND '2022-02-21T14:57:07.000Z'" username=gally
panic: runtime error: index out of range [0] with length 0

goroutine 9250 [running]:
github.com/mithrandie/csvq/lib/query.evalSubqueryForValue({0x111edc0, 0xc0001be8d0}, 0x0, {0xc0000c2b60, {0x0, {0x0, 0x0}, {0x7ff8762063b8, 0xc0007961c0}, {0x0, ...}, ...}})
	/home/gallypette/go/pkg/mod/github.com/mithrandie/csvq@v1.15.2/lib/query/eval.go:526 +0x28c
github.com/mithrandie/csvq/lib/query.Evaluate({0x111edc0, 0xc0001be8d0}, 0x7dbfc9, {0x7ff8762064d8, 0xc00010e3c0})
	/home/gallypette/go/pkg/mod/github.com/mithrandie/csvq@v1.15.2/lib/query/eval.go:56 +0x95c
github.com/mithrandie/csvq/lib/query.(*View).filter.func1(0xc0001be8d0, 0x0)
	/home/gallypette/go/pkg/mod/github.com/mithrandie/csvq@v1.15.2/lib/query/view.go:1198 +0x4d
github.com/mithrandie/csvq/lib/query.evaluateSequentialRoutine({0x111edc0, 0xc0001be8d0}, 0xc000034c00, 0xc000790480, 0xc00049a0c0, 0x0, 0xc00049a140)
	/home/gallypette/go/pkg/mod/github.com/mithrandie/csvq@v1.15.2/lib/query/eval.go:115 +0x285
github.com/mithrandie/csvq/lib/query.EvaluateSequentially({0x111edc0, 0xc0001be8d0}, 0xc00018e3f0, 0xc000790480, 0xc00049a0c0)
	/home/gallypette/go/pkg/mod/github.com/mithrandie/csvq@v1.15.2/lib/query/eval.go:137 +0xa5
github.com/mithrandie/csvq/lib/query.(*View).filter(0xc000790480, {0x111edc0, 0xc0001be8d0}, 0x0, {0x7ff8762064d8, 0xc00010e3c0})
	/home/gallypette/go/pkg/mod/github.com/mithrandie/csvq@v1.15.2/lib/query/view.go:1197 +0x12d
github.com/mithrandie/csvq/lib/query.(*View).Where(0x111edc0, {0x111edc0, 0xc0001be8d0}, 0xc00079e6e0, {0x0, {0x7ff8762064d8, 0xc00010e3c0}})
	/home/gallypette/go/pkg/mod/github.com/mithrandie/csvq@v1.15.2/lib/query/view.go:1191 +0x38
github.com/mithrandie/csvq/lib/query.selectEntity({0x111edc0, 0xc0001be8d0}, 0x0, {0x7ff8762063b8, 0xc000796230}, 0x0)
	/home/gallypette/go/pkg/mod/github.com/mithrandie/csvq@v1.15.2/lib/query/query.go:204 +0x1de
github.com/mithrandie/csvq/lib/query.Select({0x111edc0, 0xc0001be8d0}, 0x0, {0x0, {0x0, 0x0}, {0x7ff8762063b8, 0xc000796230}, {0x0, 0x0}, ...})
	/home/gallypette/go/pkg/mod/github.com/mithrandie/csvq@v1.15.2/lib/query/query.go:126 +0x33e
github.com/mithrandie/csvq/lib/query.(*Processor).ExecuteStatement(0xc0002c5900, {0x111edc0, 0xc0001be8d0}, {0x7ff8761d43e0, 0xc00018e360})
	/home/gallypette/go/pkg/mod/github.com/mithrandie/csvq@v1.15.2/lib/query/processor.go:189 +0x7e7
github.com/mithrandie/csvq/lib/query.(*Processor).execute(0xc0001be8d0, {0x111edc0, 0xc0001be8d0}, {0xc00079e7b0, 0x1, 0xe77ee0})
	/home/gallypette/go/pkg/mod/github.com/mithrandie/csvq@v1.15.2/lib/query/processor.go:94 +0x85
github.com/mithrandie/csvq/lib/query.(*Processor).Execute(0xc0002c5900, {0x111edc0, 0xc0001be8d0}, {0xc00079e7b0, 0x1, 0x1})
	/home/gallypette/go/pkg/mod/github.com/mithrandie/csvq@v1.15.2/lib/query/processor.go:83 +0xe6
github.com/mithrandie/csvq-driver.(*Conn).exec(0xc0002e3d40, {0x111ed88, 0xc0002f78c0}, {0xc0000c0140, 0xc0003d79b0}, {0x1869eb0, 0x1, 0xc0001be600})
	/home/gallypette/go/pkg/mod/github.com/mithrandie/csvq-driver@v1.4.3/conn.go:169 +0x3bb
github.com/mithrandie/csvq-driver.(*Conn).QueryContext(0xc0002e3d40, {0x111ed88, 0xc0002f78c0}, {0xc0000c0140, 0x4}, {0x1869eb0, 0x2, 0x7ff88d8943f8})
	/home/gallypette/go/pkg/mod/github.com/mithrandie/csvq-driver@v1.4.3/conn.go:128 +0x36
database/sql.ctxDriverQuery({0x111ed88, 0xc0002f78c0}, {0x7ff87457b1b0, 0xc0002e3d40}, {0x0, 0x0}, {0xc0000c0140, 0xc00047b688}, {0x1869eb0, 0x0, ...})
	/usr/lib/go-1.17/src/database/sql/ctxutil.go:48 +0x17d
database/sql.(*DB).queryDC.func1()
	/usr/lib/go-1.17/src/database/sql/sql.go:1722 +0x17d
database/sql.withLock({0x7ff8761fb500, 0xc00018ed80}, 0xc00047b7f0)
	/usr/lib/go-1.17/src/database/sql/sql.go:3396 +0x8c
database/sql.(*DB).queryDC(0xc00047b901, {0x111ed88, 0xc0002f78c0}, {0x0, 0x0}, 0xc00018ed80, 0xc00079e660, {0xc0000c0140, 0x47}, {0x0, ...})
	/usr/lib/go-1.17/src/database/sql/sql.go:1717 +0x20f
database/sql.(*DB).query(0xc0000b8000, {0x111ed88, 0xc0002f78c0}, {0xc0000c0140, 0x47}, {0x0, 0x0, 0x0}, 0x1b)
	/usr/lib/go-1.17/src/database/sql/sql.go:1700 +0x105
database/sql.(*DB).QueryContext(0x111ed50, {0x111ed88, 0xc0002f78c0}, {0xc0000c0140, 0x47}, {0x0, 0x0, 0x0})
	/usr/lib/go-1.17/src/database/sql/sql.go:1674 +0xdf
plugin/unnamed-26351e23e7071146ba4c419d606891190234cada.(*plugin).Search(0xc0002c5280, 0xc0002fe680)
	/home/gallypette/Git/graphoscope/plugins/src/file/csv/csv.go:93 +0x155
main.querySources.func1()
	/home/gallypette/Git/graphoscope/api.go:144 +0x4e
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/gallypette/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/gallypette/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
exit status 2
```

**Comment by aleksejsv** [comment]
Please try the latest version - has it improved the service on your side too?

**Comment by gallypette** [comment]
Yep - it is solved!
thank you.
